"""Package 13, Tier 4 — docs/DATA-QUALITY.md, regenerated by the audit.

Runs validate_data.py, audit_data.py, reconcile.py and snapshot_stats.py
as libraries (imported and called directly, not shelled out to) so this
reads each one's own ERRORS/WARNINGS/FLAGS lists directly rather than
re-parsing printed text — the doc can never drift from what the checks
themselves actually found. Renders one Markdown file: what was checked,
what passed, what is flagged and why, per module.

    python scripts/generate_data_quality_doc.py

Each module runs independently — one failing (e.g. reconcile.py finding
no network) does not stop the other three from still being reported;
that failure is itself rendered, not swallowed.
"""
from __future__ import annotations

import contextlib
import datetime as dt
import io
import sys
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import ROOT, log  # noqa: E402

OUT_PATH = ROOT / "docs" / "DATA-QUALITY.md"


def _run_module(display_name: str, module_name: str, command_hint: str) -> dict:
    result = {"name": display_name, "module": module_name, "command": command_hint,
              "ran": False, "exit_code": None, "log": "", "errors": [], "warnings": [], "flags": [],
              "exception": None}
    try:
        module = __import__(module_name)
    except Exception:  # noqa: BLE001 — a broken module import must still render, not crash the doc
        result["exception"] = traceback.format_exc()
        return result

    for listname in ("ERRORS", "WARNINGS", "FLAGS"):
        if hasattr(module, listname):
            getattr(module, listname).clear()

    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            result["exit_code"] = module.main()
        result["ran"] = True
    except Exception:  # noqa: BLE001 — same: render the failure, don't abort the whole doc
        result["exception"] = traceback.format_exc()
    result["log"] = buf.getvalue()
    result["errors"] = list(getattr(module, "ERRORS", []))
    result["warnings"] = list(getattr(module, "WARNINGS", []))
    result["flags"] = list(getattr(module, "FLAGS", []))
    for listname in ("ERRORS", "WARNINGS", "FLAGS"):
        if hasattr(module, listname):
            getattr(module, listname).clear()
    return result


def _status_line(r: dict) -> str:
    if r["exception"]:
        return "**COULD NOT RUN** — see exception below"
    if not r["ran"]:
        return "**DID NOT RUN**"
    if r["errors"]:
        return f"**FAILED** — {len(r['errors'])} error(s)"
    if r["warnings"] or r["flags"]:
        return f"PASSED, {len(r['warnings']) + len(r['flags'])} item(s) flagged for review"
    return "PASSED, clean"


def _render_module_section(r: dict) -> list[str]:
    out = [f"## {r['name']}", "", f"`{r['command']}` — {_status_line(r)}", ""]
    if r["exception"]:
        out += ["<details><summary>Exception</summary>", "", "```", r["exception"].rstrip(), "```", "</details>", ""]
        return out
    if r["errors"]:
        out.append(f"**{len(r['errors'])} error(s):**")
        out += [f"- {e}" for e in r["errors"]]
        out.append("")
    if r["warnings"]:
        out.append(f"**{len(r['warnings'])} warning(s):**")
        out += [f"- {w}" for w in r["warnings"]]
        out.append("")
    if r["flags"]:
        out.append(f"**{len(r['flags'])} flag(s) for review:**")
        out += [f"- {f}" for f in r["flags"]]
        out.append("")
    out += ["<details><summary>Full log</summary>", "", "```", r["log"].rstrip() or "(no output)", "```",
            "</details>", ""]
    return out


def generate() -> str:
    modules = [
        ("Validate — envelope, provenance, crosswalk, normalise.py rules", "validate_data", "make validate"),
        ("Audit — Tier 1 structural invariants", "audit_data", "make audit"),
        ("Reconcile — Tier 2, live sources + independent arithmetic", "reconcile", "python scripts/reconcile.py"),
        ("Snapshot — Tier 3, drift + coverage", "snapshot_stats", "python scripts/snapshot_stats.py"),
    ]
    results = [_run_module(name, mod, cmd) for name, mod, cmd in modules]

    total_errors = sum(len(r["errors"]) for r in results)
    total_flags = sum(len(r["warnings"]) + len(r["flags"]) for r in results)
    overall = "FAILING" if total_errors else "PASSING"

    lines = [
        "<!-- Regenerated by scripts/generate_data_quality_doc.py — edit that file, not this one. -->",
        "# Data quality",
        "",
        f"_Regenerated {dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} by "
        "`scripts/generate_data_quality_doc.py`, which runs the four checks below as libraries and "
        "reports exactly what each one found — nothing here is hand-written or summarised from memory._",
        "",
        f"**Overall: {overall}** — {total_errors} error(s) across all four checks, {total_flags} item(s) "
        "flagged for review (flags don't fail the build; see each section for what they mean).",
        "",
        "| Check | Status |",
        "|---|---|",
    ]
    for r in results:
        lines.append(f"| {r['name'].split(' — ')[0]} | {_status_line(r)} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    for r in results:
        lines += _render_module_section(r)
        lines.append("---")
        lines.append("")
    lines.append(
        "See [`docs/REGRESSION-CATALOGUE.md`](REGRESSION-CATALOGUE.md) for the historical bugs each "
        "check exists to catch, and [`data/quality_history/`](../data/quality_history/) for drift "
        "snapshots over time."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    log("Generating docs/DATA-QUALITY.md...")
    text = generate()
    OUT_PATH.write_text(text, encoding="utf-8")
    log(f"  wrote {OUT_PATH.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
