"""Package 13, Tier 4 — docs/DATA-QUALITY.md, regenerated by the audit.

Runs validate_data.py, audit_data.py, reconcile.py and snapshot_stats.py
as libraries (imported and called directly, not shelled out to) so this
reads each one's own ERRORS/WARNINGS/FLAGS lists directly rather than
re-parsing printed text — the doc can never drift from what the checks
themselves actually found. Renders one Markdown file: what was checked,
what passed, what is flagged and why, per module.

    python scripts/generate_data_quality_doc.py

Each module runs independently — one failing (e.g. reconcile.py finding
no network) does not stop the other three from still being reported;
that failure is itself rendered, not swallowed.
"""
from __future__ import annotations

import contextlib
import datetime as dt
import io
import sys
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import ROOT, log  # noqa: E402

OUT_PATH = ROOT / "docs" / "DATA-QUALITY.md"


_SEVERITY_LISTS = ("ERRORS", "WARNINGS", "FLAGS", "DROPS")


def _run_module(display_name: str, module_name: str, command_hint: str, main_kwargs: dict | None = None) -> dict:
    result = {"name": display_name, "module": module_name, "command": command_hint,
              "ran": False, "exit_code": None, "log": "", "errors": [], "warnings": [], "flags": [], "drops": [],
              "exception": None}
    try:
        module = __import__(module_name)
    except Exception:  # noqa: BLE001 — a broken module import must still render, not crash the doc
        result["exception"] = traceback.format_exc()
        return result

    for listname in _SEVERITY_LISTS:
        if hasattr(module, listname):
            getattr(module, listname).clear()

    buf = io.StringIO()
    try:
        with contextlib.redirect_stdout(buf):
            result["exit_code"] = module.main(**(main_kwargs or {}))
        result["ran"] = True
    except Exception:  # noqa: BLE001 — same: render the failure, don't abort the whole doc
        result["exception"] = traceback.format_exc()
    result["log"] = buf.getvalue()
    result["errors"] = list(getattr(module, "ERRORS", []))
    result["warnings"] = list(getattr(module, "WARNINGS", []))
    result["flags"] = list(getattr(module, "FLAGS", []))
    result["drops"] = list(getattr(module, "DROPS", []))
    for listname in _SEVERITY_LISTS:
        if hasattr(module, listname):
            getattr(module, listname).clear()
    return result


def _status_line(r: dict) -> str:
    if r["exception"]:
        return "**COULD NOT RUN** — see exception below"
    if not r["ran"]:
        return "**DID NOT RUN**"
    if r["errors"] or r["drops"]:
        return f"**FAILED** — {len(r['errors']) + len(r['drops'])} error(s)"
    if r["warnings"] or r["flags"]:
        return f"PASSED, {len(r['warnings']) + len(r['flags'])} item(s) flagged for review"
    return "PASSED, clean"


def _render_module_section(r: dict) -> list[str]:
    out = [f"## {r['name']}", "", f"`{r['command']}` — {_status_line(r)}", ""]
    if r["exception"]:
        out += ["<details><summary>Exception</summary>", "", "```", r["exception"].rstrip(), "```", "</details>", ""]
        return out
    if r["errors"]:
        out.append(f"**{len(r['errors'])} error(s):**")
        out += [f"- {e}" for e in r["errors"]]
        out.append("")
    if r["drops"]:
        out.append(f"**{len(r['drops'])} drop(s) — a genuine decline, past the point of sample noise:**")
        out += [f"- {d}" for d in r["drops"]]
        out.append("")
    if r["warnings"]:
        out.append(f"**{len(r['warnings'])} warning(s):**")
        out += [f"- {w}" for w in r["warnings"]]
        out.append("")
    if r["flags"]:
        out.append(f"**{len(r['flags'])} flag(s) for review:**")
        out += [f"- {f}" for f in r["flags"]]
        out.append("")
    out += ["<details><summary>Full log</summary>", "", "```", r["log"].rstrip() or "(no output)", "```",
            "</details>", ""]
    return out


def overall_status(results: list[dict]) -> tuple[str, int, int, int]:
    """Package 14, Tier 4.2 (external audit Finding 4). Returns (overall,
    total_errors, total_flags, unverified). Extracted from generate() as
    its own pure function specifically so this — the exact computation
    that let a module which COULD NOT RUN report as "Overall: PASSING" —
    has a real regression test that constructs a crashing module's own
    result shape directly, not a re-implementation of this logic run only
    against real modules (see test_generate_data_quality_doc.py).

    unverified counts a module that raised (result['exception']) or never
    executed (not result['ran']) — its own ERRORS/DROPS lists are empty
    (nothing to sum) not because it passed, but because it never got far
    enough to check anything. Folded into `overall` alongside total_errors,
    kept SEPARATE in the return value so the rendered table can still say
    exactly how many real ERRORS exist versus how many modules simply
    never reported in."""
    unverified = sum(1 for r in results if r["exception"] or not r["ran"])
    total_errors = sum(len(r["errors"]) + len(r["drops"]) for r in results)
    total_flags = sum(len(r["warnings"]) + len(r["flags"]) for r in results)
    overall = "FAILING" if (total_errors or unverified) else "PASSING"
    return overall, total_errors, total_flags, unverified


def generate() -> str:
    modules = [
        ("Validate — envelope, provenance, crosswalk, normalise.py rules", "validate_data", "make validate", None),
        ("Audit — Tier 1 structural invariants", "audit_data", "make audit", None),
        ("Reconcile — Tier 2, live sources + independent arithmetic", "reconcile",
         "python scripts/reconcile.py", None),
        # append=False -- this doc regeneration must not itself add a real
        # entry to data/quality_history/snapshots.jsonl (adversarial review
        # finding L16: an earlier version called this module's main() the
        # same uniform way as the other three, so regenerating the DOC also
        # silently appended a SNAPSHOT — "whenever anyone ran the doc
        # generator", not "whenever the pipeline actually ran"). `make
        # snapshot` / the CLI entry point still appends normally.
        ("Snapshot — Tier 3, drift + coverage", "snapshot_stats",
         "python scripts/snapshot_stats.py", {"append": False}),
    ]
    results = [_run_module(name, mod, cmd, kwargs) for name, mod, cmd, kwargs in modules]
    overall, total_errors, total_flags, unverified = overall_status(results)

    lines = [
        "<!-- Regenerated by scripts/generate_data_quality_doc.py — edit that file, not this one. -->",
        "# Data quality",
        "",
        f"_Regenerated {dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} by "
        "`scripts/generate_data_quality_doc.py`, which runs the four checks below as libraries and "
        "reports exactly what each one found — nothing here is hand-written or summarised from memory._",
        "",
        f"**Overall: {overall}** — {total_errors} error(s) across all four checks"
        + (f", {unverified} module(s) COULD NOT RUN (counted as failing — a report claiming health it "
           "has not verified is worse than no report)" if unverified else "")
        + f", {total_flags} item(s) flagged for review (flags don't fail the build; see each section "
        "for what they mean).",
        "",
        "| Check | Status |",
        "|---|---|",
    ]
    for r in results:
        lines.append(f"| {r['name'].split(' — ')[0]} | {_status_line(r)} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    for r in results:
        lines += _render_module_section(r)
        lines.append("---")
        lines.append("")
    lines.append(
        "See [`docs/REGRESSION-CATALOGUE.md`](REGRESSION-CATALOGUE.md) for the historical bugs each "
        "check exists to catch, and [`data/quality_history/`](../data/quality_history/) for drift "
        "snapshots over time."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    log("Generating docs/DATA-QUALITY.md...")
    text = generate()
    OUT_PATH.write_text(text, encoding="utf-8")
    log(f"  wrote {OUT_PATH.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
